apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  url: aHR0cHM6Ly9naXRodWIuY29tL3RhbnZpcjRobWVkL2t1TUVSTml0b3IuZ2l0  # https://github.com/tanvir4hmed/kuMERNitor.git
  username: dGFudmlyNGhtZWQ=         # tanvir4hmed (base64)

# echo -n 'your-git-password-or-token' | base64
# Replace <YOUR_ENCODED_PASSWORD> with the base64 encoded value of your GitHub password or PAT and apply below command.

# kubectl patch secret git-secret \
#   -n argocd \
#   --type merge \
#   -p '{"data":{"password":"<BASE64_ENCODED_PASSWORD>"}}'
