apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    argocd-image-updater.argoproj.io/image-list: index.docker.io/tanvir4hmed/frontend-app
    argocd-image-updater.argoproj.io/frontend-app.update-strategy: name
    argocd-image-updater.argoproj.io/frontend-app.allow-tags: ^v\d+$
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: tanvir4hmed/frontend-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: VITE_API_URL
              value: http://kumernitor.local/api
