apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: index.docker.io/tanvir4hmed/backend-app
    argocd-image-updater.argoproj.io/backend-app.update-strategy: name
    argocd-image-updater.argoproj.io/backend-app.allow-tags: ^v\d+$
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done;']
      containers:
        - name: backend
          image: tanvir4hmed/backend-app:v3   # Will be auto-updated by Argo CD Image Updater
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: DB_DATABASE
              value: kumernitor
